version: "2"

linters:
  default: all
  disable:
    - cyclop
    - depguard
    - exhaustruct
    - funlen
    - gocognit
    - lll
    - wsl
    - wsl_v5
  settings:
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake

    varnamelen:
      ignore-names:
        - ok
        - id
        - i
        - j
