version: "2"

linters:
  default: all
  disable:
    - cyclop
    - depguard
    #- err113
    #- errchkjson
    - exhaustruct
    #- forbidigo
    - funlen
    #- gochecknoglobals
    - gocognit
    #- gosec
    #- interfacebloat
    #- ireturn
    #- lll
    #- mnd
    #- nestif
    #- nlreturn
    #- noinlineerr
    #- paralleltest
    - recvcheck
    - revive
    - tagliatelle
    - testpackage
    - unparam
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  exclusions:
    rules:
      - linters: [lll]
        source: '//nolint:'
  settings:
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - github.com/Neokil/AutoPR/internal/application/orchestrator.Service
        - github.com/Neokil/AutoPR/internal/providers.AIProvider
