version: "2"

linters:
  default: all
  disable:
    - cyclop
    - depguard
    - exhaustruct
    - funlen
    - gocognit
    - lll
    - wsl
    - wsl_v5
  settings:
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - github.com/Neokil/AutoPR/internal/application/orchestrator.Service
        - github.com/Neokil/AutoPR/internal/providers.AIProvider
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake

    varnamelen:
      ignore-names:
        - ok
        - r
        - w
        - ch
        - id
        - fs
        - b
        - f
        - u
        - m
        - s
        - t
        - e
        - i
        - j
        - a
        - rt
        - wf
        - st
