//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// Defines values for CleanupScopeRequestScope.
const (
	CleanupScopeRequestScopeAll  CleanupScopeRequestScope = "all"
	CleanupScopeRequestScopeDone CleanupScopeRequestScope = "done"
)

// Valid indicates whether the value is a known member of the CleanupScopeRequestScope enum.
func (e CleanupScopeRequestScope) Valid() bool {
	switch e {
	case CleanupScopeRequestScopeAll:
		return true
	case CleanupScopeRequestScopeDone:
		return true
	default:
		return false
	}
}

// Defines values for FlowStatus.
const (
	FlowStatusCancelled FlowStatus = "cancelled"
	FlowStatusDone      FlowStatus = "done"
	FlowStatusFailed    FlowStatus = "failed"
	FlowStatusPending   FlowStatus = "pending"
	FlowStatusRunning   FlowStatus = "running"
	FlowStatusWaiting   FlowStatus = "waiting"
)

// Valid indicates whether the value is a known member of the FlowStatus enum.
func (e FlowStatus) Valid() bool {
	switch e {
	case FlowStatusCancelled:
		return true
	case FlowStatusDone:
		return true
	case FlowStatusFailed:
		return true
	case FlowStatusPending:
		return true
	case FlowStatusRunning:
		return true
	case FlowStatusWaiting:
		return true
	default:
		return false
	}
}

// Defines values for JobStatus.
const (
	Done    JobStatus = "done"
	Failed  JobStatus = "failed"
	Queued  JobStatus = "queued"
	Running JobStatus = "running"
)

// Valid indicates whether the value is a known member of the JobStatus enum.
func (e JobStatus) Valid() bool {
	switch e {
	case Done:
		return true
	case Failed:
		return true
	case Queued:
		return true
	case Running:
		return true
	default:
		return false
	}
}

// ActionAcceptedResponse defines model for ActionAcceptedResponse.
type ActionAcceptedResponse struct {
	Action       string  `json:"action"`
	JobId        string  `json:"job_id"`
	RepoId       string  `json:"repo_id"`
	RepoPath     string  `json:"repo_path"`
	Status       string  `json:"status"`
	TicketNumber *string `json:"ticket_number,omitempty"`
}

// ActionInfo defines model for ActionInfo.
type ActionInfo struct {
	Label string `json:"label"`
	Type  string `json:"type"`
}

// ActionRequest defines model for ActionRequest.
type ActionRequest struct {
	Label    string  `json:"label"`
	Message  *string `json:"message,omitempty"`
	RepoPath string  `json:"repo_path"`
}

// CleanupScopeRequest defines model for CleanupScopeRequest.
type CleanupScopeRequest struct {
	RepoPath string                   `json:"repo_path"`
	Scope    CleanupScopeRequestScope `json:"scope"`
}

// CleanupScopeRequestScope defines model for CleanupScopeRequest.Scope.
type CleanupScopeRequestScope string

// DiscoverTicketsResponse defines model for DiscoverTicketsResponse.
type DiscoverTicketsResponse struct {
	Tickets []DiscoveredTicket `json:"tickets"`
}

// DiscoveredTicket defines model for DiscoveredTicket.
type DiscoveredTicket struct {
	TicketNumber string `json:"ticket_number"`
	Title        string `json:"title"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// ExecutionLogResponse defines model for ExecutionLogResponse.
type ExecutionLogResponse struct {
	Content          string  `json:"content"`
	Path             string  `json:"path"`
	RunId            string  `json:"run_id"`
	State            string  `json:"state"`
	StateDisplayName *string `json:"state_display_name,omitempty"`
	Timestamp        string  `json:"timestamp"`
}

// ExecutionLogsResponse defines model for ExecutionLogsResponse.
type ExecutionLogsResponse struct {
	Logs         []ExecutionLogResponse `json:"logs"`
	RepoId       string                 `json:"repo_id"`
	RepoPath     string                 `json:"repo_path"`
	TicketNumber string                 `json:"ticket_number"`
}

// FlowStatus defines model for FlowStatus.
type FlowStatus string

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Frontend    string `json:"frontend"`
	QueueDepth  int    `json:"queue_depth"`
	ServerState string `json:"server_state"`
	Status      string `json:"status"`
}

// JobStatus defines model for JobStatus.
type JobStatus string

// JobStatusResponse defines model for JobStatusResponse.
type JobStatusResponse struct {
	Action       string     `json:"action"`
	CreatedAt    time.Time  `json:"created_at"`
	Error        *string    `json:"error,omitempty"`
	FinishedAt   *time.Time `json:"finished_at,omitempty"`
	Id           string     `json:"id"`
	RepoId       string     `json:"repo_id"`
	RepoPath     string     `json:"repo_path"`
	Scope        *string    `json:"scope,omitempty"`
	StartedAt    *time.Time `json:"started_at,omitempty"`
	Status       JobStatus  `json:"status"`
	TicketNumber *string    `json:"ticket_number,omitempty"`
}

// LogEventResponse defines model for LogEventResponse.
type LogEventResponse struct {
	Body      string `json:"body"`
	Timestamp string `json:"timestamp"`
	Title     string `json:"title"`
}

// MoveToStateRequest defines model for MoveToStateRequest.
type MoveToStateRequest struct {
	RepoPath string `json:"repo_path"`
	Target   string `json:"target"`
}

// RepoRequest defines model for RepoRequest.
type RepoRequest struct {
	RepoPath string `json:"repo_path"`
}

// RepositoryListResponse defines model for RepositoryListResponse.
type RepositoryListResponse struct {
	Repositories []string `json:"repositories"`
}

// ServerEvent defines model for ServerEvent.
type ServerEvent struct {
	Action       *string `json:"action,omitempty"`
	Error        *string `json:"error,omitempty"`
	JobId        *string `json:"job_id,omitempty"`
	PrUrl        *string `json:"pr_url,omitempty"`
	RepoId       *string `json:"repo_id,omitempty"`
	RepoPath     *string `json:"repo_path,omitempty"`
	Scope        *string `json:"scope,omitempty"`
	Status       *string `json:"status,omitempty"`
	TicketNumber *string `json:"ticket_number,omitempty"`
	Title        *string `json:"title,omitempty"`
	Type         string  `json:"type"`
}

// StateRunResponse defines model for StateRunResponse.
type StateRunResponse struct {
	ArtifactRef      *string   `json:"artifact_ref,omitempty"`
	Id               string    `json:"id"`
	LogRef           *string   `json:"log_ref,omitempty"`
	StartedAt        time.Time `json:"started_at"`
	StateDisplayName *string   `json:"state_display_name,omitempty"`
	StateName        string    `json:"state_name"`
}

// TicketArtifactResponse defines model for TicketArtifactResponse.
type TicketArtifactResponse struct {
	Content      string `json:"content"`
	Name         string `json:"name"`
	Path         string `json:"path"`
	RepoId       string `json:"repo_id"`
	RepoPath     string `json:"repo_path"`
	TicketNumber string `json:"ticket_number"`
}

// TicketDetailsResponse defines model for TicketDetailsResponse.
type TicketDetailsResponse struct {
	AvailableActions []ActionInfo        `json:"available_actions"`
	GithubBlobBase   *string             `json:"github_blob_base,omitempty"`
	NextSteps        *string             `json:"next_steps,omitempty"`
	RepoId           string              `json:"repo_id"`
	RepoPath         string              `json:"repo_path"`
	State            TicketStateResponse `json:"state"`
	Ticket           *TicketPayload      `json:"ticket,omitempty"`
	TicketNumber     string              `json:"ticket_number"`
	WorkflowStates   []WorkflowStateInfo `json:"workflow_states"`
}

// TicketEventsResponse defines model for TicketEventsResponse.
type TicketEventsResponse struct {
	Events       []LogEventResponse `json:"events"`
	RepoId       string             `json:"repo_id"`
	RepoPath     string             `json:"repo_path"`
	TicketNumber string             `json:"ticket_number"`
}

// TicketListResponse defines model for TicketListResponse.
type TicketListResponse struct {
	RepoId   *string                 `json:"repo_id,omitempty"`
	RepoPath *string                 `json:"repo_path,omitempty"`
	Tickets  []TicketSummaryResponse `json:"tickets"`
}

// TicketPayload defines model for TicketPayload.
type TicketPayload struct {
	Title                *string                `json:"title,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// TicketStateResponse defines model for TicketStateResponse.
type TicketStateResponse struct {
	BranchName   string              `json:"branch_name"`
	CreatedAt    time.Time           `json:"created_at"`
	CurrentRunId *string             `json:"current_run_id,omitempty"`
	CurrentState string              `json:"current_state"`
	FlowStatus   FlowStatus          `json:"flow_status"`
	LastError    *string             `json:"last_error,omitempty"`
	PrUrl        *string             `json:"pr_url,omitempty"`
	StateHistory *[]StateRunResponse `json:"state_history,omitempty"`
	TicketNumber string              `json:"ticket_number"`
	UpdatedAt    time.Time           `json:"updated_at"`
	WorktreePath string              `json:"worktree_path"`
}

// TicketSummaryResponse defines model for TicketSummaryResponse.
type TicketSummaryResponse struct {
	Approved     bool                 `json:"approved"`
	Busy         bool                 `json:"busy"`
	Jobs         *[]JobStatusResponse `json:"jobs,omitempty"`
	LastError    *string              `json:"last_error,omitempty"`
	PrUrl        *string              `json:"pr_url,omitempty"`
	RepoId       string               `json:"repo_id"`
	RepoPath     string               `json:"repo_path"`
	Status       FlowStatus           `json:"status"`
	TicketNumber string               `json:"ticket_number"`
	Title        *string              `json:"title,omitempty"`
	UpdatedAt    time.Time            `json:"updated_at"`
}

// WorkflowStateInfo defines model for WorkflowStateInfo.
type WorkflowStateInfo struct {
	DisplayName *string `json:"display_name,omitempty"`
	Name        string  `json:"name"`
}

// ArtifactName defines model for ArtifactName.
type ArtifactName = string

// RepoPathQuery defines model for RepoPathQuery.
type RepoPathQuery = string

// TicketID defines model for TicketID.
type TicketID = string

// ListTicketsParams defines parameters for ListTickets.
type ListTicketsParams struct {
	RepoPath *string `form:"repo_path,omitempty" json:"repo_path,omitempty"`
}

// GetTicketParams defines parameters for GetTicket.
type GetTicketParams struct {
	RepoPath RepoPathQuery `form:"repo_path" json:"repo_path"`
}

// GetTicketArtifactParams defines parameters for GetTicketArtifact.
type GetTicketArtifactParams struct {
	RepoPath RepoPathQuery `form:"repo_path" json:"repo_path"`
}

// GetTicketEventsParams defines parameters for GetTicketEvents.
type GetTicketEventsParams struct {
	RepoPath RepoPathQuery `form:"repo_path" json:"repo_path"`
}

// GetExecutionLogsParams defines parameters for GetExecutionLogs.
type GetExecutionLogsParams struct {
	RepoPath RepoPathQuery `form:"repo_path" json:"repo_path"`
}

// CleanupScopeJSONRequestBody defines body for CleanupScope for application/json ContentType.
type CleanupScopeJSONRequestBody = CleanupScopeRequest

// DiscoverTicketsJSONRequestBody defines body for DiscoverTickets for application/json ContentType.
type DiscoverTicketsJSONRequestBody = RepoRequest

// ApplyActionJSONRequestBody defines body for ApplyAction for application/json ContentType.
type ApplyActionJSONRequestBody = ActionRequest

// CleanupTicketJSONRequestBody defines body for CleanupTicket for application/json ContentType.
type CleanupTicketJSONRequestBody = RepoRequest

// MoveTicketToStateJSONRequestBody defines body for MoveTicketToState for application/json ContentType.
type MoveTicketToStateJSONRequestBody = MoveToStateRequest

// RunTicketJSONRequestBody defines body for RunTicket for application/json ContentType.
type RunTicketJSONRequestBody = RepoRequest

// Getter for additional properties for TicketPayload. Returns the specified
// element and whether it was found
func (a TicketPayload) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for TicketPayload
func (a *TicketPayload) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for TicketPayload to handle AdditionalProperties
func (a *TicketPayload) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for TicketPayload to handle AdditionalProperties
func (a TicketPayload) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Title != nil {
		object["title"], err = json.Marshal(a.Title)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'title': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /api/cleanup)
	CleanupScope(w http.ResponseWriter, r *http.Request)

	// (POST /api/discover-tickets)
	DiscoverTickets(w http.ResponseWriter, r *http.Request)

	// (GET /api/health)
	GetHealth(w http.ResponseWriter, r *http.Request)

	// (GET /api/jobs/{id})
	GetJob(w http.ResponseWriter, r *http.Request, id string)

	// (GET /api/repositories)
	ListRepositories(w http.ResponseWriter, r *http.Request)

	// (GET /api/tickets)
	ListTickets(w http.ResponseWriter, r *http.Request, params ListTicketsParams)

	// (GET /api/tickets/{id})
	GetTicket(w http.ResponseWriter, r *http.Request, id TicketID, params GetTicketParams)

	// (POST /api/tickets/{id}/action)
	ApplyAction(w http.ResponseWriter, r *http.Request, id TicketID)

	// (GET /api/tickets/{id}/artifacts/{name})
	GetTicketArtifact(w http.ResponseWriter, r *http.Request, id TicketID, name ArtifactName, params GetTicketArtifactParams)

	// (POST /api/tickets/{id}/cleanup)
	CleanupTicket(w http.ResponseWriter, r *http.Request, id TicketID)

	// (GET /api/tickets/{id}/events)
	GetTicketEvents(w http.ResponseWriter, r *http.Request, id TicketID, params GetTicketEventsParams)

	// (GET /api/tickets/{id}/execution-logs)
	GetExecutionLogs(w http.ResponseWriter, r *http.Request, id TicketID, params GetExecutionLogsParams)

	// (POST /api/tickets/{id}/move-to-state)
	MoveTicketToState(w http.ResponseWriter, r *http.Request, id TicketID)

	// (POST /api/tickets/{id}/run)
	RunTicket(w http.ResponseWriter, r *http.Request, id TicketID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CleanupScope operation middleware
func (siw *ServerInterfaceWrapper) CleanupScope(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CleanupScope(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DiscoverTickets operation middleware
func (siw *ServerInterfaceWrapper) DiscoverTickets(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DiscoverTickets(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetJob operation middleware
func (siw *ServerInterfaceWrapper) GetJob(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRepositories operation middleware
func (siw *ServerInterfaceWrapper) ListRepositories(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRepositories(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTickets operation middleware
func (siw *ServerInterfaceWrapper) ListTickets(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTicketsParams

	// ------------- Optional query parameter "repo_path" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "repo_path", r.URL.Query(), &params.RepoPath, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo_path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTickets(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTicket operation middleware
func (siw *ServerInterfaceWrapper) GetTicket(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id TicketID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTicketParams

	// ------------- Required query parameter "repo_path" -------------

	if paramValue := r.URL.Query().Get("repo_path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "repo_path"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "repo_path", r.URL.Query(), &params.RepoPath, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo_path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTicket(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ApplyAction operation middleware
func (siw *ServerInterfaceWrapper) ApplyAction(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id TicketID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ApplyAction(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTicketArtifact operation middleware
func (siw *ServerInterfaceWrapper) GetTicketArtifact(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id TicketID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "name" -------------
	var name ArtifactName

	err = runtime.BindStyledParameterWithOptions("simple", "name", r.PathValue("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTicketArtifactParams

	// ------------- Required query parameter "repo_path" -------------

	if paramValue := r.URL.Query().Get("repo_path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "repo_path"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "repo_path", r.URL.Query(), &params.RepoPath, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo_path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTicketArtifact(w, r, id, name, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CleanupTicket operation middleware
func (siw *ServerInterfaceWrapper) CleanupTicket(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id TicketID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CleanupTicket(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTicketEvents operation middleware
func (siw *ServerInterfaceWrapper) GetTicketEvents(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id TicketID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTicketEventsParams

	// ------------- Required query parameter "repo_path" -------------

	if paramValue := r.URL.Query().Get("repo_path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "repo_path"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "repo_path", r.URL.Query(), &params.RepoPath, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo_path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTicketEvents(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetExecutionLogs operation middleware
func (siw *ServerInterfaceWrapper) GetExecutionLogs(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id TicketID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetExecutionLogsParams

	// ------------- Required query parameter "repo_path" -------------

	if paramValue := r.URL.Query().Get("repo_path"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "repo_path"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "repo_path", r.URL.Query(), &params.RepoPath, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repo_path", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExecutionLogs(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MoveTicketToState operation middleware
func (siw *ServerInterfaceWrapper) MoveTicketToState(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id TicketID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MoveTicketToState(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RunTicket operation middleware
func (siw *ServerInterfaceWrapper) RunTicket(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id TicketID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RunTicket(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/cleanup", wrapper.CleanupScope)
	m.HandleFunc("POST "+options.BaseURL+"/api/discover-tickets", wrapper.DiscoverTickets)
	m.HandleFunc("GET "+options.BaseURL+"/api/health", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/api/jobs/{id}", wrapper.GetJob)
	m.HandleFunc("GET "+options.BaseURL+"/api/repositories", wrapper.ListRepositories)
	m.HandleFunc("GET "+options.BaseURL+"/api/tickets", wrapper.ListTickets)
	m.HandleFunc("GET "+options.BaseURL+"/api/tickets/{id}", wrapper.GetTicket)
	m.HandleFunc("POST "+options.BaseURL+"/api/tickets/{id}/action", wrapper.ApplyAction)
	m.HandleFunc("GET "+options.BaseURL+"/api/tickets/{id}/artifacts/{name}", wrapper.GetTicketArtifact)
	m.HandleFunc("POST "+options.BaseURL+"/api/tickets/{id}/cleanup", wrapper.CleanupTicket)
	m.HandleFunc("GET "+options.BaseURL+"/api/tickets/{id}/events", wrapper.GetTicketEvents)
	m.HandleFunc("GET "+options.BaseURL+"/api/tickets/{id}/execution-logs", wrapper.GetExecutionLogs)
	m.HandleFunc("POST "+options.BaseURL+"/api/tickets/{id}/move-to-state", wrapper.MoveTicketToState)
	m.HandleFunc("POST "+options.BaseURL+"/api/tickets/{id}/run", wrapper.RunTicket)

	return m
}

type ErrorResponseJSONResponse ErrorResponse

type CleanupScopeRequestObject struct {
	Body *CleanupScopeJSONRequestBody
}

type CleanupScopeResponseObject interface {
	VisitCleanupScopeResponse(w http.ResponseWriter) error
}

type CleanupScope202JSONResponse ActionAcceptedResponse

func (response CleanupScope202JSONResponse) VisitCleanupScopeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type CleanupScope400JSONResponse struct{ ErrorResponseJSONResponse }

func (response CleanupScope400JSONResponse) VisitCleanupScopeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CleanupScope500JSONResponse ErrorResponse

func (response CleanupScope500JSONResponse) VisitCleanupScopeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CleanupScope503JSONResponse ErrorResponse

func (response CleanupScope503JSONResponse) VisitCleanupScopeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type DiscoverTicketsRequestObject struct {
	Body *DiscoverTicketsJSONRequestBody
}

type DiscoverTicketsResponseObject interface {
	VisitDiscoverTicketsResponse(w http.ResponseWriter) error
}

type DiscoverTickets200JSONResponse DiscoverTicketsResponse

func (response DiscoverTickets200JSONResponse) VisitDiscoverTicketsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DiscoverTickets400JSONResponse struct{ ErrorResponseJSONResponse }

func (response DiscoverTickets400JSONResponse) VisitDiscoverTicketsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DiscoverTickets500JSONResponse ErrorResponse

func (response DiscoverTickets500JSONResponse) VisitDiscoverTicketsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse HealthResponse

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetJobRequestObject struct {
	Id string `json:"id"`
}

type GetJobResponseObject interface {
	VisitGetJobResponse(w http.ResponseWriter) error
}

type GetJob200JSONResponse JobStatusResponse

func (response GetJob200JSONResponse) VisitGetJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetJob404JSONResponse struct{ ErrorResponseJSONResponse }

func (response GetJob404JSONResponse) VisitGetJobResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListRepositoriesRequestObject struct {
}

type ListRepositoriesResponseObject interface {
	VisitListRepositoriesResponse(w http.ResponseWriter) error
}

type ListRepositories200JSONResponse RepositoryListResponse

func (response ListRepositories200JSONResponse) VisitListRepositoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListTicketsRequestObject struct {
	Params ListTicketsParams
}

type ListTicketsResponseObject interface {
	VisitListTicketsResponse(w http.ResponseWriter) error
}

type ListTickets200JSONResponse TicketListResponse

func (response ListTickets200JSONResponse) VisitListTicketsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListTickets400JSONResponse struct{ ErrorResponseJSONResponse }

func (response ListTickets400JSONResponse) VisitListTicketsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListTickets500JSONResponse ErrorResponse

func (response ListTickets500JSONResponse) VisitListTicketsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetTicketRequestObject struct {
	Id     TicketID `json:"id"`
	Params GetTicketParams
}

type GetTicketResponseObject interface {
	VisitGetTicketResponse(w http.ResponseWriter) error
}

type GetTicket200JSONResponse TicketDetailsResponse

func (response GetTicket200JSONResponse) VisitGetTicketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTicket400JSONResponse struct{ ErrorResponseJSONResponse }

func (response GetTicket400JSONResponse) VisitGetTicketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetTicket404JSONResponse ErrorResponse

func (response GetTicket404JSONResponse) VisitGetTicketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetTicket500JSONResponse ErrorResponse

func (response GetTicket500JSONResponse) VisitGetTicketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ApplyActionRequestObject struct {
	Id   TicketID `json:"id"`
	Body *ApplyActionJSONRequestBody
}

type ApplyActionResponseObject interface {
	VisitApplyActionResponse(w http.ResponseWriter) error
}

type ApplyAction202JSONResponse ActionAcceptedResponse

func (response ApplyAction202JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type ApplyAction400JSONResponse struct{ ErrorResponseJSONResponse }

func (response ApplyAction400JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ApplyAction500JSONResponse ErrorResponse

func (response ApplyAction500JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ApplyAction503JSONResponse ErrorResponse

func (response ApplyAction503JSONResponse) VisitApplyActionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetTicketArtifactRequestObject struct {
	Id     TicketID     `json:"id"`
	Name   ArtifactName `json:"name"`
	Params GetTicketArtifactParams
}

type GetTicketArtifactResponseObject interface {
	VisitGetTicketArtifactResponse(w http.ResponseWriter) error
}

type GetTicketArtifact200JSONResponse TicketArtifactResponse

func (response GetTicketArtifact200JSONResponse) VisitGetTicketArtifactResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTicketArtifact400JSONResponse struct{ ErrorResponseJSONResponse }

func (response GetTicketArtifact400JSONResponse) VisitGetTicketArtifactResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetTicketArtifact404JSONResponse ErrorResponse

func (response GetTicketArtifact404JSONResponse) VisitGetTicketArtifactResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetTicketArtifact500JSONResponse ErrorResponse

func (response GetTicketArtifact500JSONResponse) VisitGetTicketArtifactResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CleanupTicketRequestObject struct {
	Id   TicketID `json:"id"`
	Body *CleanupTicketJSONRequestBody
}

type CleanupTicketResponseObject interface {
	VisitCleanupTicketResponse(w http.ResponseWriter) error
}

type CleanupTicket202JSONResponse ActionAcceptedResponse

func (response CleanupTicket202JSONResponse) VisitCleanupTicketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type CleanupTicket400JSONResponse struct{ ErrorResponseJSONResponse }

func (response CleanupTicket400JSONResponse) VisitCleanupTicketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CleanupTicket500JSONResponse ErrorResponse

func (response CleanupTicket500JSONResponse) VisitCleanupTicketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CleanupTicket503JSONResponse ErrorResponse

func (response CleanupTicket503JSONResponse) VisitCleanupTicketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetTicketEventsRequestObject struct {
	Id     TicketID `json:"id"`
	Params GetTicketEventsParams
}

type GetTicketEventsResponseObject interface {
	VisitGetTicketEventsResponse(w http.ResponseWriter) error
}

type GetTicketEvents200JSONResponse TicketEventsResponse

func (response GetTicketEvents200JSONResponse) VisitGetTicketEventsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTicketEvents400JSONResponse struct{ ErrorResponseJSONResponse }

func (response GetTicketEvents400JSONResponse) VisitGetTicketEventsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetTicketEvents500JSONResponse ErrorResponse

func (response GetTicketEvents500JSONResponse) VisitGetTicketEventsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetExecutionLogsRequestObject struct {
	Id     TicketID `json:"id"`
	Params GetExecutionLogsParams
}

type GetExecutionLogsResponseObject interface {
	VisitGetExecutionLogsResponse(w http.ResponseWriter) error
}

type GetExecutionLogs200JSONResponse ExecutionLogsResponse

func (response GetExecutionLogs200JSONResponse) VisitGetExecutionLogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetExecutionLogs400JSONResponse struct{ ErrorResponseJSONResponse }

func (response GetExecutionLogs400JSONResponse) VisitGetExecutionLogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetExecutionLogs404JSONResponse ErrorResponse

func (response GetExecutionLogs404JSONResponse) VisitGetExecutionLogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetExecutionLogs500JSONResponse ErrorResponse

func (response GetExecutionLogs500JSONResponse) VisitGetExecutionLogsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type MoveTicketToStateRequestObject struct {
	Id   TicketID `json:"id"`
	Body *MoveTicketToStateJSONRequestBody
}

type MoveTicketToStateResponseObject interface {
	VisitMoveTicketToStateResponse(w http.ResponseWriter) error
}

type MoveTicketToState202JSONResponse ActionAcceptedResponse

func (response MoveTicketToState202JSONResponse) VisitMoveTicketToStateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type MoveTicketToState400JSONResponse struct{ ErrorResponseJSONResponse }

func (response MoveTicketToState400JSONResponse) VisitMoveTicketToStateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type MoveTicketToState500JSONResponse ErrorResponse

func (response MoveTicketToState500JSONResponse) VisitMoveTicketToStateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type MoveTicketToState503JSONResponse ErrorResponse

func (response MoveTicketToState503JSONResponse) VisitMoveTicketToStateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type RunTicketRequestObject struct {
	Id   TicketID `json:"id"`
	Body *RunTicketJSONRequestBody
}

type RunTicketResponseObject interface {
	VisitRunTicketResponse(w http.ResponseWriter) error
}

type RunTicket202JSONResponse ActionAcceptedResponse

func (response RunTicket202JSONResponse) VisitRunTicketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type RunTicket400JSONResponse struct{ ErrorResponseJSONResponse }

func (response RunTicket400JSONResponse) VisitRunTicketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RunTicket500JSONResponse ErrorResponse

func (response RunTicket500JSONResponse) VisitRunTicketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RunTicket503JSONResponse ErrorResponse

func (response RunTicket503JSONResponse) VisitRunTicketResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /api/cleanup)
	CleanupScope(ctx context.Context, request CleanupScopeRequestObject) (CleanupScopeResponseObject, error)

	// (POST /api/discover-tickets)
	DiscoverTickets(ctx context.Context, request DiscoverTicketsRequestObject) (DiscoverTicketsResponseObject, error)

	// (GET /api/health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)

	// (GET /api/jobs/{id})
	GetJob(ctx context.Context, request GetJobRequestObject) (GetJobResponseObject, error)

	// (GET /api/repositories)
	ListRepositories(ctx context.Context, request ListRepositoriesRequestObject) (ListRepositoriesResponseObject, error)

	// (GET /api/tickets)
	ListTickets(ctx context.Context, request ListTicketsRequestObject) (ListTicketsResponseObject, error)

	// (GET /api/tickets/{id})
	GetTicket(ctx context.Context, request GetTicketRequestObject) (GetTicketResponseObject, error)

	// (POST /api/tickets/{id}/action)
	ApplyAction(ctx context.Context, request ApplyActionRequestObject) (ApplyActionResponseObject, error)

	// (GET /api/tickets/{id}/artifacts/{name})
	GetTicketArtifact(ctx context.Context, request GetTicketArtifactRequestObject) (GetTicketArtifactResponseObject, error)

	// (POST /api/tickets/{id}/cleanup)
	CleanupTicket(ctx context.Context, request CleanupTicketRequestObject) (CleanupTicketResponseObject, error)

	// (GET /api/tickets/{id}/events)
	GetTicketEvents(ctx context.Context, request GetTicketEventsRequestObject) (GetTicketEventsResponseObject, error)

	// (GET /api/tickets/{id}/execution-logs)
	GetExecutionLogs(ctx context.Context, request GetExecutionLogsRequestObject) (GetExecutionLogsResponseObject, error)

	// (POST /api/tickets/{id}/move-to-state)
	MoveTicketToState(ctx context.Context, request MoveTicketToStateRequestObject) (MoveTicketToStateResponseObject, error)

	// (POST /api/tickets/{id}/run)
	RunTicket(ctx context.Context, request RunTicketRequestObject) (RunTicketResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CleanupScope operation middleware
func (sh *strictHandler) CleanupScope(w http.ResponseWriter, r *http.Request) {
	var request CleanupScopeRequestObject

	var body CleanupScopeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CleanupScope(ctx, request.(CleanupScopeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CleanupScope")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CleanupScopeResponseObject); ok {
		if err := validResponse.VisitCleanupScopeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DiscoverTickets operation middleware
func (sh *strictHandler) DiscoverTickets(w http.ResponseWriter, r *http.Request) {
	var request DiscoverTicketsRequestObject

	var body DiscoverTicketsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DiscoverTickets(ctx, request.(DiscoverTicketsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DiscoverTickets")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DiscoverTicketsResponseObject); ok {
		if err := validResponse.VisitDiscoverTicketsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetJob operation middleware
func (sh *strictHandler) GetJob(w http.ResponseWriter, r *http.Request, id string) {
	var request GetJobRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetJob(ctx, request.(GetJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetJob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetJobResponseObject); ok {
		if err := validResponse.VisitGetJobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListRepositories operation middleware
func (sh *strictHandler) ListRepositories(w http.ResponseWriter, r *http.Request) {
	var request ListRepositoriesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListRepositories(ctx, request.(ListRepositoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListRepositories")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListRepositoriesResponseObject); ok {
		if err := validResponse.VisitListRepositoriesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTickets operation middleware
func (sh *strictHandler) ListTickets(w http.ResponseWriter, r *http.Request, params ListTicketsParams) {
	var request ListTicketsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTickets(ctx, request.(ListTicketsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTickets")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTicketsResponseObject); ok {
		if err := validResponse.VisitListTicketsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTicket operation middleware
func (sh *strictHandler) GetTicket(w http.ResponseWriter, r *http.Request, id TicketID, params GetTicketParams) {
	var request GetTicketRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTicket(ctx, request.(GetTicketRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTicket")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTicketResponseObject); ok {
		if err := validResponse.VisitGetTicketResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ApplyAction operation middleware
func (sh *strictHandler) ApplyAction(w http.ResponseWriter, r *http.Request, id TicketID) {
	var request ApplyActionRequestObject

	request.Id = id

	var body ApplyActionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ApplyAction(ctx, request.(ApplyActionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApplyAction")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ApplyActionResponseObject); ok {
		if err := validResponse.VisitApplyActionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTicketArtifact operation middleware
func (sh *strictHandler) GetTicketArtifact(w http.ResponseWriter, r *http.Request, id TicketID, name ArtifactName, params GetTicketArtifactParams) {
	var request GetTicketArtifactRequestObject

	request.Id = id
	request.Name = name
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTicketArtifact(ctx, request.(GetTicketArtifactRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTicketArtifact")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTicketArtifactResponseObject); ok {
		if err := validResponse.VisitGetTicketArtifactResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CleanupTicket operation middleware
func (sh *strictHandler) CleanupTicket(w http.ResponseWriter, r *http.Request, id TicketID) {
	var request CleanupTicketRequestObject

	request.Id = id

	var body CleanupTicketJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CleanupTicket(ctx, request.(CleanupTicketRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CleanupTicket")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CleanupTicketResponseObject); ok {
		if err := validResponse.VisitCleanupTicketResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTicketEvents operation middleware
func (sh *strictHandler) GetTicketEvents(w http.ResponseWriter, r *http.Request, id TicketID, params GetTicketEventsParams) {
	var request GetTicketEventsRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTicketEvents(ctx, request.(GetTicketEventsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTicketEvents")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTicketEventsResponseObject); ok {
		if err := validResponse.VisitGetTicketEventsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetExecutionLogs operation middleware
func (sh *strictHandler) GetExecutionLogs(w http.ResponseWriter, r *http.Request, id TicketID, params GetExecutionLogsParams) {
	var request GetExecutionLogsRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetExecutionLogs(ctx, request.(GetExecutionLogsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetExecutionLogs")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetExecutionLogsResponseObject); ok {
		if err := validResponse.VisitGetExecutionLogsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// MoveTicketToState operation middleware
func (sh *strictHandler) MoveTicketToState(w http.ResponseWriter, r *http.Request, id TicketID) {
	var request MoveTicketToStateRequestObject

	request.Id = id

	var body MoveTicketToStateJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.MoveTicketToState(ctx, request.(MoveTicketToStateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "MoveTicketToState")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(MoveTicketToStateResponseObject); ok {
		if err := validResponse.VisitMoveTicketToStateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RunTicket operation middleware
func (sh *strictHandler) RunTicket(w http.ResponseWriter, r *http.Request, id TicketID) {
	var request RunTicketRequestObject

	request.Id = id

	var body RunTicketJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RunTicket(ctx, request.(RunTicketRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RunTicket")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RunTicketResponseObject); ok {
		if err := validResponse.VisitRunTicketResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
